services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_dest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: elements
      POSTGRES_USER: unstructured
      POSTGRES_PASSWORD: test
    volumes:
      - ./create-postgres-schema.sql:/docker-entrypoint-initdb.d/init.sql
