name: Ingest Test Fixtures Update PR

on:
  push:
  
env:
  GHA_CACHE_KEY_VERSION: "v1"

jobs:
  setup:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'ingest-test-fixtures-update'))
    env:
      NLTK_DATA: ${{ github.workspace }}/nltk_data
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: virtualenv-cache
        with:
          path: |
            .venv
            nltk_data
          key: unstructured-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.GHA_CACHE_KEY_VERSION }}-${{ hashFiles('requirements/*.txt') }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup virtual environment (no cache hit)
        run: |
          python${{ env.PYTHON_VERSION }} -m venv .venv
          source .venv/bin/activate
          [ ! -d "$NLTK_DATA" ] && mkdir "$NLTK_DATA"
          make install-ci

  update-fixtures-and-pr:
    runs-on: ubuntu-latest
    env:
      NLTK_DATA: ${{ github.workspace }}/nltk_data
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: virtualenv-cache
        with:
          path: |
            .venv
            nltk_data
          key: unstructured-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.GHA_CACHE_KEY_VERSION }}-${{ hashFiles('requirements/*.txt') }}
      - name: Setup virtual environment (no cache hit)
        run: |
          python${{ env.PYTHON_VERSION }} -m venv .venv
          source .venv/bin/activate
          mkdir "$NLTK_DATA"
          make install-ci
      - name: Update test fixtures
        env:
          GH_READ_ONLY_ACCESS_TOKEN: ${{ secrets.GH_READ_ONLY_ACCESS_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GCP_INGEST_SERVICE_KEY: ${{ secrets.GCP_INGEST_SERVICE_KEY }}
          OVERWRITE_FIXTURES: "true"
        run: |
          source .venv/bin/activate
          sudo apt-get update
          sudo apt-get install -y libmagic-dev poppler-utils libreoffice pandoc
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr5
          sudo apt-get install -y tesseract-ocr
          tesseract --version
          make install-ingest-s3
          make install-ingest-azure
          make install-ingest-discord
          make install-ingest-gcs
          make install-ingest-google-drive
          make install-ingest-github
          make install-ingest-gitlab
          make install-ingest-slack
          make install-ingest-wikipedia
#          ./test_unstructured_ingest/test-ingest.sh
#          make install
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
